
spring.application.name=Stapubox-Booking-Service

# 1. Database Connection Logic
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:sports_booking}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Am@931063}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# 3. JACKSON 3 FIX (The only way to stop the crash)
spring.mvc.format.date-time=iso
spring.jackson.default-property-inclusion=non_null